# Generated by Django 5.2.10 on 2026-01-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(help_text='HTML content', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt_br',
            field=models.TextField(help_text='HTML content', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_en',
            field=models.CharField(help_text='Short one-line description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_pt_br',
            field=models.CharField(help_text='Short one-line description', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='HTML content'),
        ),
    ]
